env: dev
kube-prometheus-stack:
  defaultRules: # The default rules are turned off because of thanos ruler. 
    create: false
  namespaceOverride: "prometheus-monitoring-dev"
  prometheus:
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true
      interval: 5s
    #Enabling this creates a service to expose thanos-sidecar outside the cluster.
    thanosServiceExternal:
      enabled: true
      type: LoadBalancer

    prometheusSpec:
      thanos:
        objectStorageConfig:
          existingSecret:
            key: thanos.yaml
            name: thanos-objstore-config
      externalLabels:
        cluster: ""

  prometheusOperator:
    thanosImage:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.34.1  
  
  grafana:
    enabled: false

  alertmanager:
    enabled: false
  