# Configuration for kube-prometheus-stack
kube-prometheus-stack:
  grafana:
    enabled: true
    # resources: 
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    defaultDashboardsEnabled: true
    defaultDashboardsTimezone: utc
    service:
      type: NodePort
      annotations: 
        # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  # prometheus.yaml 
    persistence:
      enabled: true
      type: pvc
      size: 5G
    grafana.ini:
      server: 
        root_url:
      auth.azuread:
        name: Azure AD
        enabled: true
        allow_sign_up: true
        auto_login: false
        client_id: 
        client_secret: 
        scopes: openid email profile
        auth_url: 
        token_url: 
        role_attribute_strict: false
        # allow_assign_grafana_admin: false
        # skip_org_role_sync: false
    assertNoLeakedSecrets: false
    dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'grafana-dashboards-kubernetes'
            orgId: 1
            folder: 'Kubernetes'
            type: file
            disableDeletion: true
            editable: true
            options:
              path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes

  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      inhibit_rules:
        - source_matchers:
            - 'severity = critical'
          target_matchers:
            - 'severity =~ warning|info'
          equal:
            - 'namespace'
            - 'alertname'
        - source_matchers:
            - 'severity = warning'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
            - 'alertname'
        - source_matchers:
            - 'alertname = InfoInhibitor'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
      route:
        group_by: ['namespace','cluster']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 5h
        receiver: 'null'
        routes:
        - receiver: 'pager1'
          group_by: ['cluster']
          # group_by:
          #   - alertname
          matchers:
            - cluster =~ "prod"
            # - alertname =~ "InfoInhibitor|Watchdog"
        - receiver: 'pager2'
          group_by: ['cluster']
          matchers:
            - cluster =~ "qa"
            # - alertname =~ "InfoInhibitor|Watchdog"

      receivers:
      - name: 'null'
      - name: 'pager1'
        webhook_configs:
          - url: 
            send_resolved: true
      - name: pager2
        webhook_configs:
          - url: 
            send_resolved: true
      templates:
      - '/etc/alertmanager/config/*.tmpl'

  defaultRules:
    create: false
    rules:
      alertmanager: false
      etcd: false
      general: false
      kubeControllerManager: false
      kubelet: false
      kubeProxy: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
      prometheus: false
    disabled:
      KubeletPodStartUpLatencyHigh: true

  prometheus:
    thanosService:
      enabled: true 
    thanosServiceMonitor:
      enabled: true
      interval: 5s
    #Enabling this creates a service to expose thanos-sidecar outside the cluster.
    thanosServiceExternal:
      enabled: false
    prometheusSpec:
      enableRemoteWriteReceiver: true
      thanos:
        objectStorageConfig:
          existingSecret:
            key: thanos.yaml
            name: thanos-objstore-config
      externalLabels:
        cluster: "thanos-cluster"
      storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

  prometheusOperator:
    revisionHistoryLimit: 3

  kube-state-metrics:
    prometheus:
      monitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    selfMonitor:
      enabled: true