groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'
- name: PostgreSQL
  rules:
  - alert: '[PostgreSQL] Instance Down'
    annotations:
      description: PostgreSQL instance is unavailable
    expr: |
      pg_up == 0
    for: 10m
    labels:
      severity: critical
  - alert: '[PostgreSQL] Low UpTime'
    annotations:
      description: The PostgreSQL instance has a UpTime of less than 1 hour
    expr: |
      (time() - pg_postmaster_start_time_seconds)< 3600
    for: 10m
    labels:
      severity: critical
  - alert: '[PostgreSQL] Max Write Buffer Reached'
    annotations:
      description: Background writer stops because it reached the maximum write
        buffers
    expr: |
      rate(pg_stat_bgwriter_maxwritten_clean[5m]) > 0
    for: 10m
    labels:
      severity: critical
  - alert: '[PostgreSQL] High WAL Files Archive Error Rate'
    annotations:
      description: High error rate in WAL files archiver
    expr: |
      rate(pg_stat_archiver_failed_count[5m]) /(rate(pg_stat_archiver_archived_count[5m]) + rate(pg_stat_archiver_failed_count[5m]))> 0.1
    for: 10m
    labels:
      severity: critical
  - alert: '[PostgreSQL] Low Available Connections'
    annotations:
      description: Low available network connections
    expr: |
      sum  (pg_stat_activity_count)/( sum  (pg_settings_max_connections) - sum  (pg_settings_superuser_reserved_connections)) > 0.85
    for: 10m
    labels:
      severity: critical
  - alert: '[PostgreSQL] High Response Time'
    annotations:
      description: High response time in at least one of the databases
    expr: |
      avg by (datname) (rate(pg_stat_activity_max_tx_duration{datname!~'template.*'}[5m]))> (2 * 60)
    for: 10m
    labels:
      severity: critical
  - alert: '[PostgreSQL] Low Cache Hit Rate'
    annotations:
      description: Low cache hit rate
    expr: |
      avg  (rate(pg_stat_database_blks_hit{datname!~'template.*'}[5m]) / (rate(pg_stat_database_blks_hit{datname!~'template.*'}[5m]) + rate(pg_stat_database_blks_read{datname!~'template.*'}[5m]) )) < 0.9
    for: 10m
    labels:
      severity: critical
  - alert: '[PostgreSQL] DeadLocks In Database'
    annotations:
      description: Deadlocks detected in database
    expr: |
      rate(pg_stat_database_deadlocks{datname!~'template.*'}[5m]) > 0
    for: 10m
    labels:
      severity: critical